END_POINT = "http://68.183.178.189:4000"
API_UPDATE_LOCATION = END_POINT + "api/v1/update/location"
API_LOGIN = END_POINT + "/api/v1/user/login"
API_UPDATE_LOCATION = END_POINT + "/api/v1/update/location"
API_UPDATE_GAS = END_POINT + "/api/v1/update/gas"
API_PUSH_NOTIFICATION =  END_POINT + "/api/v1/notify"
API_CREATE_TRIP = END_POINT + "/api/v1/createtrip"
API_UPDATE_TRIPDATA = END_POINT + "/api/v1/update/tripdata"
